/* Moja logo ikona za web brovser kao image x-icon. Izgled icon je crveno slovo M sa providnom pozadinom*/
const char fav_icon[] PROGMEM = R"=====(
    AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAANwD/
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEREAAAAAEREREQAA
    AAARERERAAAAABEREREAAAAAEREREQAAAAARERERAAAAABEREREAARAAEREREQAREQARERERAREREBERERERERERERER
    EREREREREREREREREREREREREAEREREREREAABEREREREAAAAREREREAAAAAEREP8AAAD/AAAA/wAAAP8AAAD/AAAA/w
    AAAOcAAADDAAAAgQAAAAAAAAAAAAAAAAAAABgAAAA8AAAAfgAAAP8AAA    
)=====";
const char fav_icon2[] PROGMEM = R"=====(
    <link href="data:image/x-icon;base64,
    AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAANwD/
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEREAAAAAEREREQAA
    AAARERERAAAAABEREREAAAAAEREREQAAAAARERERAAAAABEREREAARAAEREREQAREQARERERAREREBERERERERERERER
    EREREREREREREREREREREREREAEREREREREAABEREREREAAAAREREREAAAAAEREP8AAAD/AAAA/wAAAP8AAAD/AAAA/w
    AAAOcAAADDAAAAgQAAAAAAAAAAAAAAAAAAABgAAAA8AAAAfgAAAP8AAA" 
    rel="icon" type="image/x-icon" />    
)=====";

/*  Ovo je rezervna ikona koja je moguca opcija.
    Inace oblak, sunce i plavo nebo - standardna ikona za weather station sajtove   */
const char fav_icon1[] PROGMEM = R"=====(
    <link href="data:image/x-icon;base64,
    AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACEdDAK+q0yB
    9N5l4fjiaPr442j9+ONo/fjjaP3442j9+ONo/fjjaP344mf69N5m4cGuToElIA4CAAAAAAAAAAC+pUmB/eFm//3hZv/9
    4Wb//eFm//3hZv/94Wb//eFm//3hZv/94Wb//eFm//3hZv/94Wb/w6pLgQAAAAAAAAAA8c5b4fzXYP/812D//Ndg//zX
    YP/812D//Ndg//zXYP/812D//Ndg//zXYP/812D//Ndg//LOXOEAAAAAAAAAAPTHV/r6zFn/+sxZ//rMWv/71nj/+9h9
    //vYff/72H7/+9h+//vYff/7z2L/+sxZ//rMWf/0x1f6AAAAAAAAAADzvFD9+cBS//nAUv/85rr///37///9+////fv/
    //37///9+////fv//vnu//rMcv/5wFL/87xQ/QAAAAAAAAAA8q9J/fezS//3s0r//fLh//r79f/9+vP///ry///68v//
    +vL///ry///68v/84bb/97NK//KvSf0AAAAAAAAAAPCjQf32pkP/ubpz/2/z9P/Y/v//4/7+//X58f/+9uv//vbr//72
    6//+9uv/+9ao//amQ//wo0H9AAAAAAAAAADvljr985k8/yXf5/8K6P7/evP+/9r8///d/P3//fPl//7z5P/+8+T//OLF
    //WkT//0mjv/75Y6/QAAAAAAAAAA7Yoz/eaRPf8K2/3/Ctv+/yjg/v/J+P7/1Pr///nw4v/96NX/9J1Q//KNNP/yjTT/
    8o00/+2KM/0AAAAAAAAAAOt+LP3xgS3/N8DT/wrP/v8Kz/7/J9X+/47b5f/3uIj/8o9F//GBLf/xgS3/8YEt//GBLf/r
    fiz9AAAAAAAAAADqcyb673Yn/86BRf8+s8v/DMT6/zi10f/GhE3/73Yn/+92J//vdif/73Yn/+92J//vdif/6nMm+gAA
    AAAAAAAA5Gkh4e1sIv/tbCL/7Wwi/+1sIv/tbCL/7Wwi/+1sIv/tbCL/7Wwi/+1sIv/tbCL/7Wwi/+VpIOEAAAAAAAAA
    ALVPF4HsZB3/7GQd/+xkHf/sZB3/7GQd/+xkHf/sZB3/7GQd/+xkHf/sZB3/7GQd/+xkHf+6UReBAAAAAAAAAAAjDwQC
    t0sUgeNaGeHmWxn65lsZ/eZbGf3mXBn95lsZ/eZbGf3mWxr95lsZ+uNbGeG5TBWBJhAEAgAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAMADAACAAQAAgAEAAIAB
    AACAAQAAgAEAAIABAACAAQAAgAEAAIABAACAAQAAgAEAAIABAADAAwAA//8AAA==" 
    rel="icon" type="image/x-icon" />
)=====";